home := env_var("HOME")
path := env_var("PATH")

export LIBCLANG_PATH := home + "/.rustup/toolchains/esp/xtensa-esp32-elf-clang/esp-15.0.0-20221201/esp-clang/lib"

# If anyone knows a better way to do this let me know.
export PATH := replace("HOME/.rustup/toolchains/esp/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin:HOME/.rustup/toolchains/esp/xtensa-esp32s3-elf/esp-12.2.0_20230208/xtensa-esp32s3-elf/bin:HOME/.rustup/toolchains/esp/xtensa-esp32s2-elf/esp-12.2.0_20230208/xtensa-esp32s2-elf/bin:HOME/.rustup/toolchains/esp/riscv32-esp-elf/esp-12.2.0_20230208/riscv32-esp-elf/bin:", "HOME", home) + path

build:
	cargo build
run:
	cargo run
run-release:
	cargo run --release

clean:
	cargo clean
